"""Task templates; raw instructions remain editable before every run."""

TASKS = [
    dict(id="voice_design", group="Generate", title="Voice design", audio=False,
         route="speech", description="Describe a voice and synthesize new speech.",
         instruction="A warm, relaxed female voice, speaking clearly at a natural pace.",
         text="Welcome back. Let's make something worth listening to.", duration=5),
    dict(id="voice_clone", group="Generate", title="Voice cloning", audio=True,
         route="speech", description="Speak new text using the reference speaker. No transcript is needed with an explicit duration.",
         instruction="", text="欢迎回来。今天过得怎么样？", duration=4),
    dict(id="content_edit", group="Content", title="Replace / insert / delete words", audio=True,
         route="edit", description="Change what is said. Set a target length that can accommodate the new words.",
         instruction="Replace 'Tuesday' with 'Thursday'. Keep the speaker and surrounding content.", duration=None),
    dict(id="lyric_edit", group="Content", title="Lyric editing", audio=True,
         route="edit", description="Rewrite lyrics while asking to preserve the melody and singer.",
         instruction="Replace the lyric 'yesterday' with 'far away', preserving the melody and singer's voice.", duration=None),
    dict(id="pitch", group="Acoustic", title="Pitch", audio=True, route="edit",
         description="Try ±1, ±2, or ±3 semitones; listen for changes in speaker identity.",
         instruction="Raise the pitch by 2 semitones while keeping the content unchanged.", duration=None),
    dict(id="speed", group="Acoustic", title="Speaking speed", audio=True, route="edit",
         description="Duration is source length ÷ speed factor unless explicitly overridden.",
         instruction="Adjust the speech speed to 1.25x.", duration=None),
    dict(id="volume", group="Acoustic", title="Volume", audio=True, route="edit",
         description="Try ±5, ±10, or ±15 dB. Compare achieved loudness and clipping.",
         instruction="Increase the volume by 5 dB while preserving the content and voice.", duration=None),
    dict(id="emotion", group="Delivery", title="Emotion", audio=True, route="edit",
         description="Change delivery while asking to preserve the words and speaker.",
         instruction="Make the speaker sound happy and excited while preserving the content and voice.", duration=None),
    dict(id="timbre", group="Delivery", title="Timbre", audio=True, route="edit",
         description="Describe a different timbre while keeping the spoken content.",
         instruction="Make the voice deeper, warmer, and slightly husky, keeping the content unchanged.", duration=None),
    dict(id="accent", group="Delivery", title="Remove accent", audio=True, route="edit",
         description="Try standard Mandarin or accent reduction; check pronunciation and identity.",
         instruction="请去除这段语音的地方口音，转换为标准普通话，保留说话人的音色和内容。", duration=None),
    dict(id="nonverbal", group="Delivery", title="Breaths / laughs / coughs", audio=True, route="edit",
         description="Add or remove a nonverbal sound. Adjust duration when adding events.",
         instruction="Remove the coughs while preserving all spoken words and the speaker's voice.", duration=None),
    dict(id="whisper", group="Delivery", title="Speech → whisper", audio=True, route="edit",
         description="Convert normal speech into a whisper.",
         instruction="Convert this speech into a soft whisper while preserving the speaker and content.", duration=None),
    dict(id="unwhisper", group="Delivery", title="Whisper → speech", audio=True, route="edit",
         description="Restore a normal speaking voice from whispered speech.",
         instruction="Convert this whispered speech into a normal speaking voice while preserving the speaker and content.", duration=None),
    dict(id="denoise", group="Restore", title="Remove noise", audio=True, route="edit",
         description="Ask to remove noise while retaining other acoustic characteristics.",
         instruction="Remove only the background noise, preserve everything else, and output audio of the same length.", duration=None),
    dict(id="dereverb", group="Restore", title="Remove reverberation", audio=True, route="edit",
         description="Reduce room reverberation without requesting other changes.",
         instruction="Remove only the room reverberation, preserve everything else, and output audio of the same length.", duration=None),
    dict(id="enhance", group="Restore", title="Clean speech", audio=True, route="edit",
         description="Remove both noise and room reverberation.",
         instruction="Preserve all speakers, remove noise and reverberation, and output clean speech of the same length.", duration=None),
    dict(id="restore", group="Restore", title="Repair / bandwidth restoration", audio=True, route="edit",
         description="Describe telephone coloration, clipping, dropouts, or muffled speech. Output remains 24 kHz.",
         instruction="Remove the telephone coloration and restore natural, clear, wideband speech while preserving the speaker and content.", duration=None),
    dict(id="speaker_separation", group="Separate", title="Select speaker by order", audio=True, route="edit",
         description="Identify which speaker to retain by the order they begin speaking.",
         instruction="Keep only the second speaker to start talking and remove all other speakers. Output audio of the same length.", duration=None),
    dict(id="target_speaker", group="Separate", title="Select speaker by words", audio=True, route="edit",
         description="Identify the desired speaker using words they say in this clip.",
         instruction="Keep only the speaker who says 'hello everyone' and remove the other speakers.", duration=None),
    dict(id="vocals", group="Separate", title="Extract singing / human voices", audio=True, route="edit",
         description="Extract singing from music, or edit the instruction to retain all human voices.",
         instruction="Extract only the singing voice and remove the instrumental accompaniment. Keep the original duration.", duration=None),
    dict(id="custom", group="Explore", title="Free-form instruction", audio=False, route="edit",
         description="Use any AuK instruction, with optional source audio. Text-only requests need a duration.",
         instruction="Generate a calm, reassuring voice saying: 'Take your time. We can work through this together.'", duration=5),
]
BY_ID = {task["id"]: task for task in TASKS}
